# Generated by Django 4.2.16 on 2024-10-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
        ('network', '0004_alter_ippool_name_alter_router_name'),
        ('client', '0004_alter_client_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pppoe_username', models.CharField(max_length=50, unique=True)),
                ('pppoe_password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.ippool')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.router')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff.tariff')),
            ],
        ),
    ]
