# Generated by Django 4.2.16 on 2024-10-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientService',
        ),
    ]
