# Generated by Django 4.2.16 on 2024-10-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=20)),
                ('express_shortcode', models.CharField(max_length=20)),
                ('shortcode_type', models.CharField(choices=[('paybill', 'Paybill'), ('till_number', 'Till Number')], max_length=20)),
                ('passkey', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'M-Pesa Configuration',
                'verbose_name_plural': 'M-Pesa Configurations',
            },
        ),
    ]
