# Generated by Django 4.2.16 on 2024-10-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_mpesaconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesaconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='mpesaconfig',
            name='express_shortcode',
        ),
        migrations.RemoveField(
            model_name='mpesaconfig',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mpesaconfig',
            name='shortcode_type',
        ),
        migrations.AlterField(
            model_name='mpesaconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
