# Generated by Django 4.2.16 on 2024-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_mpesaconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesaconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
