# Generated by Django 4.2.16 on 2024-10-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ippool',
            name='router',
        ),
    ]
