# Generated by Django 4.2.16 on 2024-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_ippool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippool',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
