# Generated by Django 4.2.16 on 2024-10-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_alter_client_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('acct_session_id', models.CharField(max_length=64)),
                ('acct_unique_id', models.CharField(max_length=32)),
                ('acct_input_octets', models.BigIntegerField()),
                ('acct_output_octets', models.BigIntegerField()),
                ('acct_terminate_cause', models.CharField(max_length=32)),
                ('acct_start_time', models.DateTimeField()),
                ('acct_stop_time', models.DateTimeField(blank=True, null=True)),
                ('framed_ip_address', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'radacct',
            },
        ),
        migrations.CreateModel(
            name='RadiusReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radreply',
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('download_speed', models.IntegerField()),
                ('upload_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RadiusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('attribute', models.CharField(default='Cleartext-Password', max_length=64)),
                ('op', models.CharField(default=':=', max_length=2)),
                ('value', models.CharField(max_length=253)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'radcheck',
            },
        ),
    ]
