# Generated by Django 4.2.16 on 2024-10-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RadiusAccounting',
        ),
        migrations.RemoveField(
            model_name='radiusprofile',
            name='client',
        ),
        migrations.DeleteModel(
            name='RadiusReply',
        ),
        migrations.DeleteModel(
            name='ServicePlan',
        ),
        migrations.DeleteModel(
            name='RadiusProfile',
        ),
    ]
