# Generated by Django 4.2.16 on 2024-10-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0006_delete_clientservice'),
        ('tariff', '0001_initial'),
        ('network', '0004_alter_ippool_name_alter_router_name'),
        ('service', '0002_delete_radiusaccounting_remove_radiusprofile_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPPoEService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_services', to='client.client')),
                ('ip_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.ippool')),
                ('router', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.router')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff.tariff')),
            ],
        ),
    ]
