# Generated by Django 4.2.16 on 2024-10-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pppoeservice',
            name='is_active',
        ),
    ]
