# Generated by Django 4.2.16 on 2024-10-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_delete_clientservice'),
        ('service', '0004_remove_pppoeservice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pppoeservice',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_service', to='client.client'),
        ),
    ]
