# Generated by Django 4.2.16 on 2024-10-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_pppoeservice_mikrotik_secret_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppoeservice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pppoeservice',
            name='last_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoeservice',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
