# Generated by Django 4.2.16 on 2024-10-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_pppoeservice_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pppoeservice',
            name='is_active',
        ),
    ]
